#!/bin/sh
myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the authentik Appliance!

To keep this VM secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

To finish setting up your authentik instance, open http://$myip/if/flow/initial-setup/

On the server:
  * The generated credentials are saved under /srv/authentik/.env
  * Backups are saved under /srv/authentik/backups
  * To upgrade authentik, run "ak appliance upgrade"

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
