#!/bin/bash

cd /srv/authentik

echo "AK_APPLIANCE={{ appliance_vendor }}" >> .env
echo "PG_PASS=$(pwgen 40 1)" >> .env
echo "AUTHENTIK_SECRET_KEY=$(pwgen 50 1)" >> .env
# Skip if you don't want to enable error reporting
echo "AUTHENTIK_ERROR_REPORTING__ENABLED=true" >> .env
echo "AUTHENTIK_ERROR_REPORTING__ENVIRONMENT={{ appliance_vendor }}" >> .env

ak appliance start
ak backup
